// The steps of the migration: the codemods, then the residual patch on top.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runCodemods } from '../codemods/index.js';
import { createFileAccess } from './files.js';
import {
  diffOptions,
  git,
  repositoryRoot,
  resolveCommit,
  stageAll,
  withTemporaryWorktree,
} from './git.js';

export const toolDir = path.dirname(import.meta.dirname);
export const patchFile = path.join(toolDir, 'residual.patch');

// The changes of the target that the patch leaves out, as they only belong on
// the esm branch or are generated. --verify ignores them.
export const leftOut = {
  // Files the patch doesn't touch.
  files: new Map([
    ['package-lock.json', 'regenerated by the migration with `npm install --package-lock-only`'],
    ['.github/workflows/docs.yml', 'the esm branch only stops the docs deployment'],
  ]),
  // Settings the patch keeps as they are on the base.
  settings: [
    {
      file: '.github/workflows/test.yml',
      pattern: /^( +branches: \[)esm(\])$/gm,
      replacement: '$1main$2',
      description: 'the branches CI runs on',
    },
  ],
};

// Describes what --verify ignores.
export function describeLeftOut() {
  return [
    ...[...leftOut.files].map(([file, reason]) => `${file}: ${reason}`),
    ...leftOut.settings.map(({ file, description }) => `${file}: ${description}`),
  ];
}

// A pathspec for the diffs that leaves out these scripts and the files above.
export function diffPathspec() {
  return [
    '--',
    '.',
    ...excludeTool(),
    ...[...leftOut.files.keys()].map((file) => `:(exclude)${file}`),
  ];
}

// The tree of `commit` with the esm branch's settings reverted to the base's.
export function targetTree(repo, commit, { log }) {
  return withTemporaryIndex(repo, commit, (env) => {
    for (const { file, pattern, replacement } of leftOut.settings) {
      const { status, output } = git(repo, ['show', `${commit}:${file}`], { allowFailure: true });
      const content = status === 0 ? output.replace(pattern, replacement) : null;
      if (content === null || content === output) {
        log(`  ${file} has no esm branch settings to leave out`);
        continue;
      }
      const blob = git(repo, ['hash-object', '-w', '--stdin'], { input: content }).trim();
      git(repo, ['update-index', '--cacheinfo', `100644,${blob},${file}`], { env });
    }
    return git(repo, ['write-tree'], { env }).trim();
  });
}

function withTemporaryIndex(repo, commit, fn) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'objection-esm-index-'));
  try {
    const env = { GIT_INDEX_FILE: path.join(dir, 'index') };
    git(repo, ['read-tree', commit], { env });
    return fn(env);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

// Runs the codemods in `root` and stages their output.
export async function runCodemodStep(root, { log }) {
  const left = await runCodemods(createFileAccess(root), { log });
  if (left.length) {
    log(`  left for the residual patch:\n${left.map((line) => `    ${line}`).join('\n')}`);
  }
  return stageAll(root);
}

// Applies the residual patch with a 3-way merge. Returns the conflicted files.
export async function applyResidualPatch(root, { log }) {
  const patch = fs.readFileSync(patchFile, 'utf8');
  await providePreimages(root, patch, { log });
  // Files that the patch deletes and that are gone already, e.g. because `main`
  // deleted them too, would make the whole patch fail.
  const deletedAlready = deletedFiles(patch).filter(
    (file) => !fs.existsSync(path.join(root, file)),
  );
  deletedAlready.forEach((file) => log(`  ${file} is deleted already`));
  // Files that the patch changes but `main` deleted would make the whole patch
  // fail as well. Like git's modify/delete conflicts, they are left out and
  // reported as conflicts.
  const deletedOnMain = modifiedFiles(patch).filter(
    (file) => !fs.existsSync(path.join(root, file)),
  );
  deletedOnMain.forEach((file) => log(`  ${file} is deleted, but changed by the patch`));
  const excludes = [...deletedAlready, ...deletedOnMain].map((file) => `--exclude=${file}`);
  const { status, output } = git(
    root,
    ['apply', '--3way', '--whitespace=nowarn', ...excludes, patchFile],
    { allowFailure: true },
  );
  const conflicts = git(root, ['diff', '--name-only', '--diff-filter=U']).trim();
  if (status !== 0 && !conflicts) {
    throw new Error(`The residual patch could not be applied:\n${output}`);
  }
  return [...(conflicts ? conflicts.split('\n') : []), ...deletedOnMain];
}

// Updates package-lock.json for the dependencies of the migrated package.json,
// as the residual patch leaves it out. Returns whether it succeeded.
export function updateLockfile(root, { log }) {
  log('updating package-lock.json');
  try {
    execFileSync(
      'npm',
      ['install', '--package-lock-only', '--ignore-scripts', '--no-audit', '--no-fund'],
      {
        cwd: root,
        stdio: ['ignore', 'ignore', 'inherit'],
      },
    );
  } catch {
    log('  npm install failed. Run `npm install --package-lock-only` yourself.');
    return false;
  }
  git(root, ['add', 'package-lock.json']);
  return true;
}

// The 3-way merge needs the files that the patch was made against: the
// codemods' output on the patch's base. If the repository lacks them, because
// the base has changed since, the codemods recreate them on that base.
async function providePreimages(root, patch, { log }) {
  const missing = preimageBlobs(patch).filter(
    (blob) => git(root, ['cat-file', '-e', blob], { allowFailure: true }).status !== 0,
  );
  const base = patchBase(patch);
  if (!missing.length || !base) {
    return;
  }
  if (git(root, ['cat-file', '-e', `${base}^{commit}`], { allowFailure: true }).status !== 0) {
    log(`  the patch's base ${base} is missing, so conflicts can't be merged`);
    return;
  }
  log(`  recreating the codemods' output on the patch's base ${base.slice(0, 10)}`);
  await withTemporaryWorktree(root, base, (dir) => runCodemodStep(dir, { log: () => {} }));
}

function deletedFiles(patch) {
  return [...patch.matchAll(/^diff --git a\/(\S+) b\/\S+\ndeleted file mode /gm)].map(
    ([, file]) => file,
  );
}

// The files that the patch changes, without the ones it adds, deletes or
// renames.
function modifiedFiles(patch) {
  return [...patch.matchAll(/^diff --git a\/(\S+) b\/(\S+)\nindex /gm)]
    .filter(([, from, to]) => from === to)
    .map(([, file]) => file);
}

function preimageBlobs(patch) {
  const blobs = [...patch.matchAll(/^index ([0-9a-f]{40,64})\.\./gm)].map(([, blob]) => blob);
  return [...new Set(blobs)].filter((blob) => !/^0+$/.test(blob));
}

// The base commit the patch was made from, recorded in its header.
export function patchBase(patch = fs.readFileSync(patchFile, 'utf8')) {
  return /^Base: ([0-9a-f]+)/m.exec(patch)?.[1] ?? null;
}

// The diff from the codemods' output on `base` to `target`.
export async function createResidualPatch(repo, { base, target, log }) {
  const baseCommit = resolveCommit(repo, base);
  const targetCommit = resolveCommit(repo, target);
  const diff = await withTemporaryWorktree(repo, baseCommit, async (dir) => {
    log(`running the codemods on ${base} (${baseCommit.slice(0, 10)})`);
    const tree = await runCodemodStep(dir, { log });
    return git(dir, [
      'diff',
      ...diffOptions,
      tree,
      targetTree(dir, targetCommit, { log }),
      ...diffPathspec(),
    ]);
  });
  const header = [
    'Residual patch of the ES module migration, applied by scripts/esm/migrate.mjs on top of',
    "the codemods' output. Regenerate it with `node scripts/esm/migrate.mjs --update-patch`.",
    '',
    `Base: ${baseCommit} (${base})`,
    `Target: ${targetCommit} (${target})`,
    '',
    'Left out of the target (see `leftOut` in lib/migration.js):',
    ...describeLeftOut().map((line) => `  ${line}`),
    '',
    '',
  ].join('\n');
  return header + diff;
}

// A pathspec that leaves out these scripts, for checkouts that have them.
export function excludeTool() {
  const repo = repositoryRoot(toolDir);
  const relative = path.relative(fs.realpathSync(repo), fs.realpathSync(toolDir));
  return [`:(exclude)${relative.split(path.sep).join('/')}`];
}
